// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.types.ts
// For now, we'll define the types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string;
          name: string;
          slug: string;
          custom_domain: string | null;
          logo_url: string | null;
          primary_color: string | null;
          settings: Json | null;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          subscription_tier: "free" | "pro" | "institution" | "enterprise";
          subscription_status: "active" | "canceled" | "past_due" | "trialing" | null;
          trial_ends_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          custom_domain?: string | null;
          logo_url?: string | null;
          primary_color?: string | null;
          settings?: Json | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          subscription_tier?: "free" | "pro" | "institution" | "enterprise";
          subscription_status?: "active" | "canceled" | "past_due" | "trialing" | null;
          trial_ends_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          custom_domain?: string | null;
          logo_url?: string | null;
          primary_color?: string | null;
          settings?: Json | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          subscription_tier?: "free" | "pro" | "institution" | "enterprise";
          subscription_status?: "active" | "canceled" | "past_due" | "trialing" | null;
          trial_ends_at?: string | null;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          tenant_id: string;
          email: string;
          full_name: string;
          avatar_url: string | null;
          role: "admin" | "instructor" | "student";
          phone: string | null;
          emergency_contact: Json | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          tenant_id: string;
          email: string;
          full_name: string;
          avatar_url?: string | null;
          role?: "admin" | "instructor" | "student";
          phone?: string | null;
          emergency_contact?: Json | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          tenant_id?: string;
          email?: string;
          full_name?: string;
          avatar_url?: string | null;
          role?: "admin" | "instructor" | "student";
          phone?: string | null;
          emergency_contact?: Json | null;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      courses: {
        Row: {
          id: string;
          tenant_id: string;
          title: string;
          description: string | null;
          course_code: string | null;
          course_type: "EMR" | "EMT" | "AEMT" | "Paramedic" | "Custom";
          instructor_id: string;
          enrollment_code: string;
          start_date: string | null;
          end_date: string | null;
          max_students: number | null;
          settings: Json | null;
          is_active: boolean;
          is_archived: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          title: string;
          description?: string | null;
          course_code?: string | null;
          course_type?: "EMR" | "EMT" | "AEMT" | "Paramedic" | "Custom";
          instructor_id: string;
          enrollment_code: string;
          start_date?: string | null;
          end_date?: string | null;
          max_students?: number | null;
          settings?: Json | null;
          is_active?: boolean;
          is_archived?: boolean;
          created_at?: string;
        };
        Update: {
          tenant_id?: string;
          title?: string;
          description?: string | null;
          course_code?: string | null;
          course_type?: "EMR" | "EMT" | "AEMT" | "Paramedic" | "Custom";
          instructor_id?: string;
          enrollment_code?: string;
          start_date?: string | null;
          end_date?: string | null;
          max_students?: number | null;
          settings?: Json | null;
          is_active?: boolean;
          is_archived?: boolean;
        };
      };
      enrollments: {
        Row: {
          id: string;
          tenant_id: string;
          course_id: string;
          student_id: string;
          enrolled_at: string;
          status: "active" | "completed" | "dropped";
          completion_percentage: number;
          final_grade: number | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          course_id: string;
          student_id: string;
          enrolled_at?: string;
          status?: "active" | "completed" | "dropped";
          completion_percentage?: number;
          final_grade?: number | null;
        };
        Update: {
          tenant_id?: string;
          course_id?: string;
          student_id?: string;
          enrolled_at?: string;
          status?: "active" | "completed" | "dropped";
          completion_percentage?: number;
          final_grade?: number | null;
        };
      };
      modules: {
        Row: {
          id: string;
          tenant_id: string;
          course_id: string;
          title: string;
          description: string | null;
          order_index: number;
          unlock_date: string | null;
          is_published: boolean;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          course_id: string;
          title: string;
          description?: string | null;
          order_index?: number;
          unlock_date?: string | null;
          is_published?: boolean;
        };
        Update: {
          tenant_id?: string;
          course_id?: string;
          title?: string;
          description?: string | null;
          order_index?: number;
          unlock_date?: string | null;
          is_published?: boolean;
        };
      };
      lessons: {
        Row: {
          id: string;
          tenant_id: string;
          module_id: string;
          title: string;
          content_type: "video" | "document" | "text" | "embed";
          content: Json | null;
          video_url: string | null;
          document_url: string | null;
          duration_minutes: number | null;
          order_index: number;
          is_published: boolean;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          module_id: string;
          title: string;
          content_type?: "video" | "document" | "text" | "embed";
          content?: Json | null;
          video_url?: string | null;
          document_url?: string | null;
          duration_minutes?: number | null;
          order_index?: number;
          is_published?: boolean;
        };
        Update: {
          tenant_id?: string;
          module_id?: string;
          title?: string;
          content_type?: "video" | "document" | "text" | "embed";
          content?: Json | null;
          video_url?: string | null;
          document_url?: string | null;
          duration_minutes?: number | null;
          order_index?: number;
          is_published?: boolean;
        };
      };
      assignments: {
        Row: {
          id: string;
          tenant_id: string;
          module_id: string;
          title: string;
          description: string | null;
          instructions: string | null;
          type: "quiz" | "written" | "skill_checklist" | "discussion";
          due_date: string | null;
          available_from: string | null;
          points_possible: number;
          time_limit_minutes: number | null;
          attempts_allowed: number;
          settings: Json | null;
          rubric: Json | null;
          is_published: boolean;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          module_id: string;
          title: string;
          description?: string | null;
          instructions?: string | null;
          type?: "quiz" | "written" | "skill_checklist" | "discussion";
          due_date?: string | null;
          available_from?: string | null;
          points_possible?: number;
          time_limit_minutes?: number | null;
          attempts_allowed?: number;
          settings?: Json | null;
          rubric?: Json | null;
          is_published?: boolean;
        };
        Update: {
          tenant_id?: string;
          module_id?: string;
          title?: string;
          description?: string | null;
          instructions?: string | null;
          type?: "quiz" | "written" | "skill_checklist" | "discussion";
          due_date?: string | null;
          available_from?: string | null;
          points_possible?: number;
          time_limit_minutes?: number | null;
          attempts_allowed?: number;
          settings?: Json | null;
          rubric?: Json | null;
          is_published?: boolean;
        };
      };
      quiz_questions: {
        Row: {
          id: string;
          tenant_id: string;
          assignment_id: string;
          question_text: string;
          question_type: "multiple_choice" | "true_false" | "matching" | "short_answer";
          options: Json | null;
          correct_answer: Json;
          points: number;
          order_index: number;
          explanation: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          assignment_id: string;
          question_text: string;
          question_type?: "multiple_choice" | "true_false" | "matching" | "short_answer";
          options?: Json | null;
          correct_answer: Json;
          points?: number;
          order_index?: number;
          explanation?: string | null;
        };
        Update: {
          tenant_id?: string;
          assignment_id?: string;
          question_text?: string;
          question_type?: "multiple_choice" | "true_false" | "matching" | "short_answer";
          options?: Json | null;
          correct_answer?: Json;
          points?: number;
          order_index?: number;
          explanation?: string | null;
        };
      };
      submissions: {
        Row: {
          id: string;
          tenant_id: string;
          assignment_id: string;
          student_id: string;
          attempt_number: number;
          content: Json | null;
          file_urls: Json | null;
          started_at: string | null;
          submitted_at: string | null;
          status: "in_progress" | "submitted" | "graded" | "returned";
          raw_score: number | null;
          curved_score: number | null;
          final_score: number | null;
          graded_by: string | null;
          graded_at: string | null;
          feedback: Json | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          assignment_id: string;
          student_id: string;
          attempt_number?: number;
          content?: Json | null;
          file_urls?: Json | null;
          started_at?: string | null;
          submitted_at?: string | null;
          status?: "in_progress" | "submitted" | "graded" | "returned";
          raw_score?: number | null;
          curved_score?: number | null;
          final_score?: number | null;
          graded_by?: string | null;
          graded_at?: string | null;
          feedback?: Json | null;
        };
        Update: {
          tenant_id?: string;
          assignment_id?: string;
          student_id?: string;
          attempt_number?: number;
          content?: Json | null;
          file_urls?: Json | null;
          started_at?: string | null;
          submitted_at?: string | null;
          status?: "in_progress" | "submitted" | "graded" | "returned";
          raw_score?: number | null;
          curved_score?: number | null;
          final_score?: number | null;
          graded_by?: string | null;
          graded_at?: string | null;
          feedback?: Json | null;
        };
      };
      skill_categories: {
        Row: {
          id: string;
          tenant_id: string;
          course_type: "EMR" | "EMT" | "AEMT" | "Paramedic";
          name: string;
          description: string | null;
          required_count: number;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          course_type: "EMR" | "EMT" | "AEMT" | "Paramedic";
          name: string;
          description?: string | null;
          required_count?: number;
          is_active?: boolean;
        };
        Update: {
          tenant_id?: string;
          course_type?: "EMR" | "EMT" | "AEMT" | "Paramedic";
          name?: string;
          description?: string | null;
          required_count?: number;
          is_active?: boolean;
        };
      };
      skills: {
        Row: {
          id: string;
          tenant_id: string;
          category_id: string;
          name: string;
          description: string | null;
          steps: Json | null;
          passing_criteria: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          category_id: string;
          name: string;
          description?: string | null;
          steps?: Json | null;
          passing_criteria?: string | null;
        };
        Update: {
          tenant_id?: string;
          category_id?: string;
          name?: string;
          description?: string | null;
          steps?: Json | null;
          passing_criteria?: string | null;
        };
      };
      skill_attempts: {
        Row: {
          id: string;
          tenant_id: string;
          skill_id: string;
          student_id: string;
          course_id: string;
          evaluator_id: string | null;
          attempt_number: number;
          status: "passed" | "failed" | "needs_practice";
          step_results: Json | null;
          notes: string | null;
          feedback: string | null;
          evaluated_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          skill_id: string;
          student_id: string;
          course_id: string;
          evaluator_id?: string | null;
          attempt_number?: number;
          status?: "passed" | "failed" | "needs_practice";
          step_results?: Json | null;
          notes?: string | null;
          feedback?: string | null;
          evaluated_at?: string | null;
        };
        Update: {
          tenant_id?: string;
          skill_id?: string;
          student_id?: string;
          course_id?: string;
          evaluator_id?: string | null;
          attempt_number?: number;
          status?: "passed" | "failed" | "needs_practice";
          step_results?: Json | null;
          notes?: string | null;
          feedback?: string | null;
          evaluated_at?: string | null;
        };
      };
      clinical_logs: {
        Row: {
          id: string;
          tenant_id: string;
          student_id: string;
          course_id: string;
          log_type: "hours" | "patient_contact";
          date: string;
          hours: number | null;
          site_name: string | null;
          site_type: string | null;
          supervisor_name: string | null;
          supervisor_credentials: string | null;
          activities: Json | null;
          patient_info: Json | null;
          skills_performed: Json | null;
          was_team_lead: boolean;
          notes: string | null;
          verification_status: "pending" | "verified" | "rejected";
          verified_by: string | null;
          verified_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          student_id: string;
          course_id: string;
          log_type: "hours" | "patient_contact";
          date: string;
          hours?: number | null;
          site_name?: string | null;
          site_type?: string | null;
          supervisor_name?: string | null;
          supervisor_credentials?: string | null;
          activities?: Json | null;
          patient_info?: Json | null;
          skills_performed?: Json | null;
          was_team_lead?: boolean;
          notes?: string | null;
          verification_status?: "pending" | "verified" | "rejected";
          verified_by?: string | null;
          verified_at?: string | null;
        };
        Update: {
          tenant_id?: string;
          student_id?: string;
          course_id?: string;
          log_type?: "hours" | "patient_contact";
          date?: string;
          hours?: number | null;
          site_name?: string | null;
          site_type?: string | null;
          supervisor_name?: string | null;
          supervisor_credentials?: string | null;
          activities?: Json | null;
          patient_info?: Json | null;
          skills_performed?: Json | null;
          was_team_lead?: boolean;
          notes?: string | null;
          verification_status?: "pending" | "verified" | "rejected";
          verified_by?: string | null;
          verified_at?: string | null;
        };
      };
      discussion_threads: {
        Row: {
          id: string;
          tenant_id: string;
          course_id: string;
          module_id: string | null;
          title: string;
          content: string;
          author_id: string;
          is_pinned: boolean;
          is_locked: boolean;
          is_anonymous_allowed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          course_id: string;
          module_id?: string | null;
          title: string;
          content: string;
          author_id: string;
          is_pinned?: boolean;
          is_locked?: boolean;
          is_anonymous_allowed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          tenant_id?: string;
          course_id?: string;
          module_id?: string | null;
          title?: string;
          content?: string;
          author_id?: string;
          is_pinned?: boolean;
          is_locked?: boolean;
          is_anonymous_allowed?: boolean;
          updated_at?: string;
        };
      };
      discussion_posts: {
        Row: {
          id: string;
          tenant_id: string;
          thread_id: string;
          parent_id: string | null;
          content: string;
          author_id: string;
          is_anonymous: boolean;
          upvotes: number;
          created_at: string;
          edited_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          thread_id: string;
          parent_id?: string | null;
          content: string;
          author_id: string;
          is_anonymous?: boolean;
          upvotes?: number;
          created_at?: string;
          edited_at?: string | null;
        };
        Update: {
          tenant_id?: string;
          thread_id?: string;
          parent_id?: string | null;
          content?: string;
          author_id?: string;
          is_anonymous?: boolean;
          upvotes?: number;
          edited_at?: string | null;
        };
      };
      events: {
        Row: {
          id: string;
          tenant_id: string;
          course_id: string;
          title: string;
          description: string | null;
          event_type: "class" | "lab" | "clinical" | "exam" | "other";
          start_time: string;
          end_time: string;
          location: string | null;
          virtual_link: string | null;
          is_mandatory: boolean;
          recurrence_rule: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          course_id: string;
          title: string;
          description?: string | null;
          event_type?: "class" | "lab" | "clinical" | "exam" | "other";
          start_time: string;
          end_time: string;
          location?: string | null;
          virtual_link?: string | null;
          is_mandatory?: boolean;
          recurrence_rule?: string | null;
        };
        Update: {
          tenant_id?: string;
          course_id?: string;
          title?: string;
          description?: string | null;
          event_type?: "class" | "lab" | "clinical" | "exam" | "other";
          start_time?: string;
          end_time?: string;
          location?: string | null;
          virtual_link?: string | null;
          is_mandatory?: boolean;
          recurrence_rule?: string | null;
        };
      };
      attendance: {
        Row: {
          id: string;
          tenant_id: string;
          event_id: string;
          student_id: string;
          status: "present" | "absent" | "late" | "excused";
          check_in_time: string | null;
          notes: string | null;
          recorded_by: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          event_id: string;
          student_id: string;
          status?: "present" | "absent" | "late" | "excused";
          check_in_time?: string | null;
          notes?: string | null;
          recorded_by?: string | null;
        };
        Update: {
          tenant_id?: string;
          event_id?: string;
          student_id?: string;
          status?: "present" | "absent" | "late" | "excused";
          check_in_time?: string | null;
          notes?: string | null;
          recorded_by?: string | null;
        };
      };
      notifications: {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          type: "assignment" | "grade" | "announcement" | "reminder";
          title: string;
          message: string;
          link: string | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          type: "assignment" | "grade" | "announcement" | "reminder";
          title: string;
          message: string;
          link?: string | null;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          tenant_id?: string;
          user_id?: string;
          type?: "assignment" | "grade" | "announcement" | "reminder";
          title?: string;
          message?: string;
          link?: string | null;
          is_read?: boolean;
        };
      };
      announcements: {
        Row: {
          id: string;
          tenant_id: string;
          course_id: string;
          title: string;
          content: string;
          author_id: string;
          is_pinned: boolean;
          publish_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          course_id: string;
          title: string;
          content: string;
          author_id: string;
          is_pinned?: boolean;
          publish_at?: string | null;
          created_at?: string;
        };
        Update: {
          tenant_id?: string;
          course_id?: string;
          title?: string;
          content?: string;
          author_id?: string;
          is_pinned?: boolean;
          publish_at?: string | null;
        };
      };
      files: {
        Row: {
          id: string;
          tenant_id: string;
          uploaded_by: string;
          filename: string;
          file_type: string;
          file_size: number;
          storage_path: string;
          context: "course" | "assignment" | "submission" | "profile";
          context_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          uploaded_by: string;
          filename: string;
          file_type: string;
          file_size: number;
          storage_path: string;
          context: "course" | "assignment" | "submission" | "profile";
          context_id?: string | null;
          created_at?: string;
        };
        Update: {
          tenant_id?: string;
          uploaded_by?: string;
          filename?: string;
          file_type?: string;
          file_size?: number;
          storage_path?: string;
          context?: "course" | "assignment" | "submission" | "profile";
          context_id?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: "admin" | "instructor" | "student";
      course_type: "EMR" | "EMT" | "AEMT" | "Paramedic" | "Custom";
      subscription_tier: "free" | "pro" | "institution" | "enterprise";
      assignment_type: "quiz" | "written" | "skill_checklist" | "discussion";
      submission_status: "in_progress" | "submitted" | "graded" | "returned";
      question_type: "multiple_choice" | "true_false" | "matching" | "short_answer";
    };
  };
}

// Helper types
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
