-- QR Code Attendance Schema — SUPERSEDED, intentionally a no-op.
--
-- This migration originally created its own `attendance_sessions` table built
-- around events and a rotating `session_code`, plus `attendance_checkins`,
-- a `check_in_student()` function and their policies.
--
-- Ten days later 20240315000000_attendance_tracking.sql introduced a different
-- `attendance_sessions` — built around a course, a scheduled_date and start/end
-- times — using CREATE TABLE IF NOT EXISTS. That is the design the application
-- actually uses and the one production runs. Because of the IF NOT EXISTS, on a
-- database that ran this file first the real table was silently skipped and
-- every later statement touching course_id, title or scheduled_date failed. That
-- single collision accounted for two of the migration failures on a clean
-- rebuild, and left a rebuilt database unable to record attendance at all.
--
-- Evidence that this branch is dead rather than merely unused:
--   * production has no `attendance_checkins` table, and its `attendance_sessions`
--     is the course-based one from 20240315
--   * no other migration in this directory references any object created here
--   * the only application code written against it —
--     src/lib/hooks/use-qr-attendance.ts, components/attendance/QRCodeDisplay.tsx
--     and components/attendance/QRScanner.tsx — is not rendered anywhere. QR
--     check-in in the running app is components/attendance/qr-attendance.tsx,
--     which uses attendance_check_in_codes from 20240315.
--
-- The body is removed rather than the file, so a migration ledger that already
-- recorded this version stays consistent. Nothing is dropped: on a database that
-- did run the original, the objects are left exactly where they are, and
-- 20260910000000_reconcile_attendance_sessions.sql brings such a database's
-- attendance_sessions up to the shape the app expects.
--
-- Do not re-add tables here. Attendance lives in 20240315000000, and the QR
-- codes in attendance_check_in_codes.

SELECT 1;
