-- QR Code Attendance Schema
-- Tracks attendance sessions and check-ins via QR code scanning

-- Attendance sessions (generated by instructors)
CREATE TABLE attendance_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_code TEXT NOT NULL,
  started_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  is_active BOOLEAN DEFAULT true,
  location_required BOOLEAN DEFAULT false,
  location_lat DECIMAL(10, 8),
  location_lng DECIMAL(11, 8),
  location_radius_meters INTEGER DEFAULT 100, -- Geofence radius
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- Each event can have multiple sessions (e.g., multiple class meetings)
  UNIQUE(event_id, session_code)
);

-- Attendance check-ins (recorded when students scan QR)
CREATE TABLE attendance_checkins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  session_id UUID NOT NULL REFERENCES attendance_sessions(id) ON DELETE CASCADE,
  student_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  checked_in_at TIMESTAMPTZ DEFAULT NOW(),
  check_in_method TEXT DEFAULT 'qr_code', -- qr_code, manual, location
  device_info TEXT,
  location_lat DECIMAL(10, 8),
  location_lng DECIMAL(11, 8),
  is_valid BOOLEAN DEFAULT true, -- Can be invalidated if fraud detected
  notes TEXT,

  -- Each student can only check in once per session
  UNIQUE(session_id, student_id)
);

-- Indexes
CREATE INDEX idx_attendance_sessions_event ON attendance_sessions(event_id);
CREATE INDEX idx_attendance_sessions_code ON attendance_sessions(session_code);
CREATE INDEX idx_attendance_sessions_active ON attendance_sessions(is_active, expires_at);
CREATE INDEX idx_attendance_checkins_session ON attendance_checkins(session_id);
CREATE INDEX idx_attendance_checkins_student ON attendance_checkins(student_id);

-- Function to generate a unique session code
CREATE OR REPLACE FUNCTION generate_attendance_session_code()
RETURNS TEXT AS $$
DECLARE
  chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  code TEXT := '';
  i INTEGER;
BEGIN
  FOR i IN 1..6 LOOP
    code := code || substr(chars, floor(random() * length(chars) + 1)::int, 1);
  END LOOP;
  RETURN code;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-generate session code on insert
CREATE OR REPLACE FUNCTION attendance_sessions_before_insert()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.session_code IS NULL OR NEW.session_code = '' THEN
    LOOP
      NEW.session_code := generate_attendance_session_code();
      EXIT WHEN NOT EXISTS (
        SELECT 1 FROM attendance_sessions
        WHERE event_id = NEW.event_id AND session_code = NEW.session_code
      );
    END LOOP;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER attendance_sessions_before_insert_trigger
  BEFORE INSERT ON attendance_sessions
  FOR EACH ROW
  EXECUTE FUNCTION attendance_sessions_before_insert();

-- Function for atomic check-in (prevents race conditions)
CREATE OR REPLACE FUNCTION check_in_student(
  p_session_code TEXT,
  p_student_id UUID,
  p_tenant_id UUID,
  p_device_info TEXT DEFAULT NULL,
  p_location_lat DECIMAL DEFAULT NULL,
  p_location_lng DECIMAL DEFAULT NULL
) RETURNS JSON AS $$
DECLARE
  v_session attendance_sessions;
  v_checkin attendance_checkins;
  v_distance DECIMAL;
BEGIN
  -- Find the active session
  SELECT * INTO v_session
  FROM attendance_sessions
  WHERE session_code = p_session_code
    AND tenant_id = p_tenant_id
    AND is_active = true
    AND expires_at > NOW()
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN json_build_object(
      'success', false,
      'error', 'Session not found or expired'
    );
  END IF;

  -- Check if student already checked in
  IF EXISTS (
    SELECT 1 FROM attendance_checkins
    WHERE session_id = v_session.id
      AND student_id = p_student_id
  ) THEN
    RETURN json_build_object(
      'success', false,
      'error', 'Already checked in'
    );
  END IF;

  -- Check location if required
  IF v_session.location_required AND v_session.location_lat IS NOT NULL THEN
    IF p_location_lat IS NULL OR p_location_lng IS NULL THEN
      RETURN json_build_object(
        'success', false,
        'error', 'Location required for check-in'
      );
    END IF;

    -- Calculate distance using Haversine formula approximation
    v_distance := 111139 * sqrt(
      pow(v_session.location_lat - p_location_lat, 2) +
      pow((v_session.location_lng - p_location_lng) * cos(radians(v_session.location_lat)), 2)
    );

    IF v_distance > v_session.location_radius_meters THEN
      RETURN json_build_object(
        'success', false,
        'error', 'You are too far from the check-in location'
      );
    END IF;
  END IF;

  -- Create the check-in
  INSERT INTO attendance_checkins (
    tenant_id,
    session_id,
    student_id,
    check_in_method,
    device_info,
    location_lat,
    location_lng
  ) VALUES (
    p_tenant_id,
    v_session.id,
    p_student_id,
    'qr_code',
    p_device_info,
    p_location_lat,
    p_location_lng
  ) RETURNING * INTO v_checkin;

  -- Also update the attendance record in the main attendance table if it exists
  UPDATE attendance
  SET status = 'present',
      check_in_time = NOW()
  WHERE event_id = v_session.event_id
    AND student_id = p_student_id;

  -- If no attendance record exists, create one
  IF NOT FOUND THEN
    INSERT INTO attendance (tenant_id, event_id, student_id, status, check_in_time)
    VALUES (p_tenant_id, v_session.event_id, p_student_id, 'present', NOW())
    ON CONFLICT DO NOTHING;
  END IF;

  RETURN json_build_object(
    'success', true,
    'checkin_id', v_checkin.id,
    'checked_in_at', v_checkin.checked_in_at
  );
END;
$$ LANGUAGE plpgsql;

-- RLS Policies

-- Attendance sessions: Instructors can manage, students can view active
ALTER TABLE attendance_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Instructors can manage attendance sessions"
  ON attendance_sessions FOR ALL
  USING (
    tenant_id = (SELECT tenant_id FROM users WHERE id = auth.uid())
    AND (SELECT role FROM users WHERE id = auth.uid()) IN ('admin', 'instructor')
  );

CREATE POLICY "Students can view active sessions"
  ON attendance_sessions FOR SELECT
  USING (
    tenant_id = (SELECT tenant_id FROM users WHERE id = auth.uid())
    AND is_active = true
    AND expires_at > NOW()
  );

-- Attendance check-ins: Students can see their own, instructors can see all
ALTER TABLE attendance_checkins ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view relevant check-ins"
  ON attendance_checkins FOR SELECT
  USING (
    tenant_id = (SELECT tenant_id FROM users WHERE id = auth.uid())
    AND (
      student_id = auth.uid()
      OR (SELECT role FROM users WHERE id = auth.uid()) IN ('admin', 'instructor')
    )
  );

CREATE POLICY "Students can check in"
  ON attendance_checkins FOR INSERT
  WITH CHECK (
    tenant_id = (SELECT tenant_id FROM users WHERE id = auth.uid())
    AND student_id = auth.uid()
  );
